# Generated by Django 5.2.1 on 2025-05-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_plan_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='会员套餐ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_plan_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='会员套餐名称'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('active', '有效'), ('expired', '已过期'), ('suspended', '已暂停'), ('cancelled', '已取消')], default='active', max_length=20, null=True, verbose_name='会员状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('staff', '员工'), ('member', '会员'), ('user', '普通用户')], default='user', help_text='用户角色：管理员、员工、会员或普通用户', max_length=10, verbose_name='角色'),
        ),
    ]
