# Generated by Django 5.2.1 on 2025-05-29 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_membership_plan_id_user_membership_plan_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Fitness Profile', 'verbose_name_plural': 'User Fitness Profiles'},
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Avatar URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='member_id',
            field=models.CharField(blank=True, help_text='Membership card number', max_length=20, null=True, unique=True, verbose_name='Member ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_end',
            field=models.DateField(blank=True, null=True, verbose_name='Membership End Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_plan_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Membership Plan ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_plan_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Membership Plan Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_start',
            field=models.DateField(blank=True, null=True, verbose_name='Membership Start Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20, null=True, verbose_name='Membership Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, null=True, verbose_name='Membership Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for login and notifications', max_length=11, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff'), ('member', 'Member'), ('user', 'Regular User')], default='user', help_text='User role: Administrator, Staff, Member or Regular User', max_length=10, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('fitness', 'Fitness'), ('wellness', 'Wellness'), ('rehabilitation', 'Rehabilitation'), ('other', 'Other')], max_length=50, null=True, verbose_name='Fitness Goal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True, verbose_name='Fitness Level'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='health_condition',
            field=models.TextField(blank=True, help_text="Record user's health condition, medical history, or precautions", null=True, verbose_name='Health Condition'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)'),
        ),
    ]
