# Generated by Django 5.2.1 on 2025-05-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('member', 'Member'), ('staff', 'Staff'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
