# Generated by Django 5.2.1 on 2025-05-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_membership_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Member ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('none', 'No Membership'), ('active', 'Active'), ('expired', 'Expired')], default='none', max_length=20, null=True, verbose_name='Membership Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('none', 'No Membership'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=20, null=True, verbose_name='Membership Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('member', 'Member'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
