# Generated by Django 3.2.11 on 2025-05-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='课程图片URL'),
        ),
    ]
