# Generated by Django 5.2.1 on 2025-05-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='Discount on additional sessions', verbose_name='Discount Percentage'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='max_sessions',
            field=models.IntegerField(default=0, help_text='0 means unlimited', verbose_name='Max Sessions per Month'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, verbose_name='Plan Type'),
        ),
    ]
