# Generated by Django 5.2.1 on 2025-05-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_membershipplan_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='discount_percentage',
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, verbose_name='Plan Type'),
        ),
    ]
